--liquibase formatted sql
--changeset husrav:lib

CREATE TABLE categories
(
    id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL
);

CREATE TABLE books
(
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       TEXT NOT NULL,
    authors     TEXT NOT NULL,
    description TEXT NOT NULL,
    path        TEXT NOT NULL,
    image       TEXT,
    category_id INT  NOT NULL REFERENCES categories (id)
);